import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: "A4",
                margin: 50,
                info: {
                    Author: "CortexAI",
                    Title: data.title || "CortexAI Document",
                    Creator: "CortexAI",
                },
            });

            const chunks = [];

            doc.on("data", (chunk) => {
                chunks.push(chunk);
            });

            doc.on("end", () => {
                console.log("🔥 PDF DOCUMENT END");

                resolve(Buffer.concat(chunks));
            });

            doc.on("error", (error) => {
                console.error("🔥 PDFKIT ERROR:", error);
                reject(error);
            });



            doc
                .fontSize(28)
                .fillColor("#111827")
                .text(data.title || "Untitled Document", {
                    align: "center",
                });


            if (data.subtitle) {
                doc.moveDown(0.5);

                doc
                    .fontSize(14)
                    .fillColor("#6B7280")
                    .text(data.subtitle, {
                        align: "center",
                    });
            }

            doc.moveDown(2);



            data.sections?.forEach((section) => {
                doc
                    .fontSize(17)
                    .fillColor("#111827")
                    .text(section.heading);

                doc.moveDown(0.5);

                section.points?.forEach((point) => {
                    doc
                        .fontSize(12)
                        .fillColor("#374151")
                        .text(`• ${point}`, {
                            lineGap: 5,
                        });

                    doc.moveDown(0.2);
                });

                doc.moveDown(1);
            });


            doc
                .fontSize(10)
                .fillColor("#9CA3AF")
                .text("Generated by CortexAI", {
                    align: "center",
                });

          
            doc.end();

        } catch (error) {
            reject(error);
        }
    });
};