name: Cortex AI Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:

  # =========================
  # BACKEND DEPLOYMENT
  # =========================
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }} 

      - name: Login to  ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Gateway
        run: |
          docker build \
           -f backend/gateway/Dockerfile \
           -f gateway backend 

      - name: tag Gateway
        run: |
            docker tag gateway:latest \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/gateway:latest

      - name: push Gateway
        run: |
            docker push \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/gateway:latest



      - name: Build Auth 
        run: |
          docker build \
           -f backend/services/auth/Dockerfile \
           -f auth-service backend 

      - name: tag Auth
        run: |
            docker tag auth-service:latest \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/auth-service:latest

      - name: push Auth
        run: |
            docker push \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/auth-service:latest
            

          
      - name: Build chat
        run: |
          docker build \
           -f backend/services/chat/Dockerfile \
           -f chat-services backend 

      - name: tag chat
        run: |
            docker tag chat-services:latest \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/chat-services:latest

      - name: push chat
        run: |
            docker push \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/chat-services:latest    



      - name: Build agent
        run: |
          docker build \
           -f backend/services/agent/Dockerfile \
           -f agent-services backend 

      - name: tag agent
        run: |
            docker tag agent-services:latest \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/agent-services:latest

      - name: push agent
        run: |
            docker push \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/agent-services:latest    


      - name: Build billing
        run: |
          docker build \
           -f backend/services/billing/Dockerfile \
           -f billing-services backend 

      - name: tag billing
        run: |
            docker tag billing-services:latest \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/billing-services:latest

      - name: push billing
        run: |
            docker push \
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/billing-services:latest  



      - name: deploy gateway
        run: |
          aws ecs update-service \
          --cluster ${{secrets.ECS_CLUSTER}} \
          --service ${{secrets.GATEWAY_SERVICE}} \
          --force-new-deployment

      - name: deploy auth
        run: |
          aws ecs update-service \
          --cluster ${{secrets.ECS_CLUSTER}} \
          --service ${{secrets.AUTH_SERVICE}} \
          --force-new-deployment

      - name: deploy chat
        run: |
          aws ecs update-service \
          --cluster ${{secrets.ECS_CLUSTER}} \
          --service ${{secrets.CHAT_SERVICE}} \
          --force-new-deployment

      - name: deploy agent
        run: |
          aws ecs update-service \
          --cluster ${{secrets.ECS_CLUSTER}} \
          --service ${{secrets.AGENT_SERVICE}} \
          --force-new-deployment

      - name: deploy billing
        run: |
          aws ecs update-service \
          --cluster ${{secrets.ECS_CLUSTER}} \
          --service ${{secrets.BILLING_SERVICE}} \
          --force-new-deployment






  # =========================
  # FRONTEND DEPLOYMENT
  # =========================
  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build frontend
        run : |
           cd frontend
           npm install
           npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }} 

      - name: upload to s3  
        run: |
          aws s3 sync \
          frontend/dist \
          s3://cortex-ai-dharmi-314567759945-ap-south-1-an \
          -- delete

      - name: invalidate cloudfront
        run: |
           aws cloudfront create-invalidation \
           --distribution-id \
           ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}} \
           --paths "/*"